<?PHP
$BarColor = array(
'#0000FF','#FF0000','#008000','#800000','#BA55D3',
'#778899','#6495ED','#FC0FC0','#8FBC8B','#D2691E',
'#7B68EE','#C0C0C0','#00CED1','#FFA500','#00FF00',
'#BC8F8F','#D8BFD8','#00FFFF','#B0E0E6','#D2B48C',
'#F4A460','#FFE4C4','#FFC0CB','#FFFF00','#000000'
);
$BarColorGradient = '#FFFFFF';
$BarBorderColor = '#cccccc';
$BarAxisColor  = '#cccccc';
$BarLightPosition = 2;
$BarColorUser = false;
$GraphBorderColor = '#eeeeee';
$GraphLayerColor  = '#FFFFFF';
$TitleColor = '#000000';
$TitleRowColor = '#000000';
$TitleColColor = '#000000';
$DataColor   = '#000000';
$GrillColorOne = '#FBFBFB';
$GrillColorTwo = '#F7F7F7';
$TitleFontType = '$a/ttf/arialnb.ttf';
$FontType	   = '$a/ttf/tahoma.ttf';
?>
